### ISSUE TITLE
WidgetKit beta updates causing minor issues

### ISSUE THREAD

**Issue by SPConrad** [apatronl/Emojibook#1]
Some updates to the TimelineProvider Protocol and WidgetConfiguration are causing minor issues within the `Provider` and `Emojibook_Widget` structs in `Emojibook_Widget.swift`.

Updates include: 

**1.** `func placeholder` has been added, replaces need for `placeholder` in `StaticConfiguration` declaration 
**2.** `func snapshot` renamed to `getSnapshot`
**3.** `func timeline` renamed to `getTimeline`

I made a very simple PR, but I'm guessing you weren't expecting anyone to do that so your settings don't allow others to create branches. I've not doubt you can handle this on your own but I'm happy to push it up if you change your settings. 

ugly copy/paste of my updates:
```
 struct Provider: TimelineProvider {
-  public typealias Entry = SimpleEntry
+  func placeholder(in context: Context) -> SimpleEntry {
+      SimpleEntry(date: Date(), emojiDetails: EmojiProvider.random())
+  }
 
-  public func snapshot(with context: Context, completion: @escaping (SimpleEntry) -> ()) {
+  public func getSnapshot(in context: Context, completion: @escaping (SimpleEntry) -> ()) {
     let entry = SimpleEntry(date: Date(), emojiDetails: EmojiProvider.random())
     completion(entry)
   }
 
-  public func timeline(with context: Context, completion: @escaping (Timeline<Entry>) -> ()) {
+  public func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> ()) {
     var entries: [SimpleEntry] = []
```

```
   public var body: some WidgetConfiguration {
     StaticConfiguration(
       kind: kind,
-      provider: Provider(),
-      placeholder: PlaceholderView()
-    ) { entry in
+      provider: Provider()) { entry in
       Emojibook_WidgetEntryView(entry: entry)
     }
     .configurationDisplayName("Random Emoji")

```

**Comment by migapple** [comment]
I did it that works

**Comment by SPConrad** [comment]
Looks like he implemented the changes. Thank you, @apatronl! 😄
